# Generated by Django 5.0.6 on 2024-07-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name_person',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='context',
            new_name='place',
        ),
    ]
