# Generated by Django 5.0.6 on 2024-07-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_event_all_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
        migrations.AlterField(
            model_name='event',
            name='name_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(default='Calp', max_length=100),
            preserve_default=False,
        ),
    ]
