# Generated by Django 5.0.6 on 2025-06-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='place',
            new_name='place_str',
        ),
    ]
