# Generated by Django 5.0.6 on 2025-06-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_event_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place_str',
        ),
    ]
