# Generated by Django 5.0.6 on 2026-01-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0011_activityassignment_activity_assignees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
