# Generated by Django 5.0.6 on 2026-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0012_alter_activity_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('OG', 'On Going'), ('OH', 'On hold'), ('C', 'Completed')], max_length=100),
        ),
    ]
