# Generated by Django 5.0.6 on 2026-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0013_alter_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='telescope',
            field=models.CharField(choices=[('Common', 'Common'), ('LST1', 'LST1'), ('LST2', 'LST2'), ('LST3', 'LST3'), ('LST4', 'LST4')], max_length=100),
        ),
    ]
