version: '3.5'

services:
  app:
    hostname: "cal_django"
    container_name: cal_app
    build: .
    command: ./entrypoint.sh
    restart: always
    volumes:
      - .:/code
      - /home/lst1/lst-onsite-availability/db_data/db.sqlite3:/db.sqlite3
      - /home/lst1/lst-onsite-availability/logs:/logs
      - static:/code/staticfiles
  nginx:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/usr/share/nginx/html/static
    depends_on:
      - app
    restart: always

volumes:
  static:
